### ISSUE TITLE
Would moving to async udp library be a benefit ?

### ISSUE THREAD

**Issue by penfold42** [forkineye/E131#10]
If so, I'm willing to have a go at porting it

**Comment by forkineye** [comment]
I'm not sure yet.  The heap is still fine last I checked so it should be able to be supported.  I won't be looking at it anytime soon though, just not enough time lately.

**Comment by forkineye** [comment]
AsyncUDP support added, still needs to be documented though. Can reference https://github.com/forkineye/ESPixelStick for implementation.

**Comment by forkineye** [comment]
Think I'll split this off into a dedicated project. Just getting too messy working around esp8266 specific stuff.

**Comment by forkineye** [comment]
ESP8266 specific Async fork is here now: https://github.com/forkineye/ESPAsyncE131.  I'll remove the async stuff from this library to clean it up.
