### ISSUE TITLE
171st Pixel

### ISSUE THREAD

**Issue by Capii1** [forkineye/E131#11]
I have a full 300 pixel strip that I'd like to use one ESP8266 NodeMCU to run however I've not been able to get the pixels after 170th to display correctly. I've tired this in both Vixen 3 and xLights both giving me the same issue. Does anyone know how to fix this problem?

**Comment by forkineye** [comment]
Configure it to use Unicast and send your pixels as consecutive universes utilizing all 512 channels.  For instance, if you set the ESPixelStick code to start on Universe 10 and channel 1, it will listen for universes 10 and 11 to get all 900 channels of data.
