### ISSUE TITLE
Ethernet  with  esp8266 and esp32 ( ethernet + esp8266 / esp32 )

### ISSUE THREAD

**Issue by joeskolengaden** [forkineye/E131#23]
Need to utilize the speed of esp8266/esp32 and the reliability of data over Ethernet. Please add support to your library

**Comment by Aircoookie** [comment]
You should be able to use this library with your external Ethernet controller. Just connect to network and then use the `e131.begin(E131_UNICAST)`. This should init the library and the UDP socket to work with ethernet. Although I think there is no issue with the WiFi reliablity if your router is close enough.
