### ISSUE TITLE
Please add to Arduino Library Manager

### ISSUE THREAD

**Issue by probonopd** [forkineye/E131#4]
Please make this library available in the Arduino [Library Manager](https://www.arduino.cc/en/Guide/Libraries#toc3). 
- Ensure your library is complaint with [1.5 format](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification)(1.5 format folder layout is not required)
- Tag it and push the tag, or create a release with github "releases"
- Open an issue on [Arduino's github](https://github.com/arduino/Arduino/issues), specifying the git repo (or github url) from where to download your library

More information on https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by forkineye** [comment]
Submitted
